package com.truecaller.qa;

/* loaded from: /home/user/tc_decoded/classes7.dex */
public final class a implements f.baz {
    public final /* synthetic */ com.truecaller.qa.Hilt_QMActivity a;

    public a(com.truecaller.qa.Hilt_QMActivity hilt_QMActivity) {
        this.a = hilt_QMActivity;
    }

    /* JADX WARN: Type inference failed for: r0v26, types: [java.lang.Object, dq1.h] */
    /* JADX WARN: Type inference failed for: r0v27, types: [wi.qux, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r13v8, types: [java.lang.Object, wt.l] */
    /* JADX WARN: Type inference failed for: r15v12, types: [java.lang.Object, ah.n] */
    /* JADX WARN: Type inference failed for: r18v2, types: [p22.bar, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r2v45, types: [java.lang.Object, k92.j] */
    /* JADX WARN: Type inference failed for: r2v77, types: [java.lang.Object, c62.b] */
    /* JADX WARN: Type inference failed for: r5v47, types: [java.lang.Object, v2.j1] */
    /* JADX WARN: Type inference failed for: r7v10, types: [java.lang.Object, f0.x0] */
    public final void a(androidx.activity.ComponentActivity componentActivity) {
        com.truecaller.qa.Hilt_QMActivity hilt_QMActivity = this.a;
        if (!hilt_QMActivity.c0) {
            hilt_QMActivity.c0 = true;
            tx.e eVar = (com.truecaller.qa.s) hilt_QMActivity.X3();
            com.truecaller.qa.QMActivity qMActivity = (com.truecaller.qa.QMActivity) hilt_QMActivity;
            tx.e eVar2 = eVar;
            tx.w wVar = eVar2.f;
            qMActivity.e0 = (mp1.bar) wVar.G0.get();
            qMActivity.f0 = (o63.b) wVar.So.get();
            qMActivity.g0 = (o63.bar) wVar.To.get();
            qMActivity.h0 = wVar.pj;
            qMActivity.i0 = (h93.baz) wVar.t7.get();
            qMActivity.j0 = (kx2.bar) wVar.q3.get();
            qMActivity.k0 = (ej0.baz) wVar.o8.get();
            qMActivity.l0 = (ij0.e) wVar.m7.get();
            qMActivity.m0 = (q81.b) wVar.S5.get();
            qMActivity.n0 = (hw0.a) wVar.h5.get();
            qMActivity.o0 = (rz0.x) wVar.v6.get();
            qMActivity.p0 = (j01.n) wVar.Zn.get();
            qMActivity.q0 = (jq2.b) wVar.L2.get();
            qMActivity.r0 = (jq2.qux) wVar.M2.get();
            tx.c0 c0Var = wVar.b;
            qMActivity.s0 = (zd2.j) c0Var.n6.get();
            qMActivity.t0 = (r31.bar) wVar.q1.get();
            qMActivity.u0 = (q11.bar) wVar.U.get();
            qMActivity.v0 = (yh2.bar) c0Var.U0.get();
            qMActivity.w0 = cd3.baz.a(wVar.G1);
            qMActivity.x0 = (n11.g) wVar.F1.get();
            qMActivity.y0 = (c73.k0) wVar.Dm.get();
            qMActivity.z0 = (vf2.bar) wVar.Wb.get();
            qMActivity.A0 = (xz1.q) wVar.L0.get();
            qMActivity.B0 = (qw2.a0) wVar.x6.get();
            qMActivity.C0 = (u03.z) wVar.M.get();
            qMActivity.D0 = (com.truecaller.qa.x) wVar.e0.get();
            qMActivity.E0 = (tf2.r) wVar.zk.get();
            qMActivity.F0 = (k71.e) wVar.Tm.get();
            qMActivity.G0 = (hz1.d) wVar.c3.get();
            qMActivity.H0 = (bw1.b) wVar.I9.get();
            qMActivity.I0 = (hz1.c) c0Var.o6.get();
            qMActivity.J0 = (uw1.d) c0Var.m6.get();
            qMActivity.K0 = (u03.b) wVar.O.get();
            qMActivity.L0 = (s62.d) wVar.P2.get();
            qMActivity.M0 = (u62.k) wVar.N2.get();
            qMActivity.N0 = (up2.qux) wVar.cr.get();
            qMActivity.O0 = c0Var.w0();
            qMActivity.P0 = (e23.qux) wVar.qk.get();
            qMActivity.Q0 = (rk0.bar) c0Var.x3.get();
            qMActivity.R0 = wVar.L0();
            ji2.j jVar = new ji2.j((android.content.Context) eVar2.i.a, (r31.bar) wVar.q1.get(), (gd0.b) wVar.Dk.get(), (gd0.a) wVar.yh.get(), (x42.a) wVar.g6.get(), (pk0.a) wVar.R.get(), (com.truecaller.qa.x) wVar.e0.get(), (b61.baz) wVar.Xo.get(), (qw2.d0) wVar.l5.get(), (u03.i0) c0Var.Q1.get(), (s03.bar) wVar.u9.get(), (xf2.a) wVar.M1.get(), (uj2.bar) c0Var.q6.get(), (pk0.baz) wVar.S.get(), (mg2.bar) wVar.q4.get(), cd3.baz.a(wVar.Xp), (jm1.d) eVar2.j0.get(), (pj1.bar) wVar.I4.get(), (uk1.a) c0Var.r6.get(), (ry.bar) wVar.B0.get());
            tx.w wVar2 = c0Var.a;
            com.moloco.sdk.xenoss.sdkdevkit.android.adrenderer.internal.vast.render.h hVar = new com.moloco.sdk.xenoss.sdkdevkit.android.adrenderer.internal.vast.render.h((android.content.Context) wVar2.I.get(), (xf0.bar) wVar2.U2.get(), (com.truecaller.qa.x) wVar2.e0.get(), (pr0.k) wVar2.q8.get(), (pr0.e1) wVar2.Pj.get(), (android.content.ContentResolver) wVar2.I0.get(), (er0.bar) c0Var.v6.get(), (n11.l) wVar2.o0.get(), (p22.bar) new java.lang.Object(), (pr0.j0) wVar2.s8.get(), (hr0.o) wVar2.Oj.get(), (hr0.f) c0Var.c3.get(), (qm0.qux) c0Var.m2.get(), c0Var.p1(), (qo1.b) wVar2.p8.get());
            eq.m0 m0Var = new eq.m0((android.content.Context) eVar2.i.a, (h93.baz) wVar.t7.get(), (com.truecaller.data.country.d) wVar.a4.get());
            y.n0 n0Var = new y.n0((android.content.Context) eVar2.i.a, c0Var.A(), (gg0.baz) c0Var.w6.get(), (xz1.q) wVar.L0.get(), (qo1.qux) wVar.d4.get(), (com.truecaller.qa.x) wVar.e0.get());
            ej.b bVar = new ej.b((android.content.Context) eVar2.i.a, (r31.bar) wVar.q1.get(), (ix1.d) wVar.D3.get(), (hz1.d) wVar.c3.get(), wVar.s2(), (bw1.b) wVar.I9.get());
            android.content.Context context = (android.content.Context) eVar2.i.a;
            f2.y yVar = new f2.y(context, (ax2.qux) wVar.fo.get());
            ga1.e G0 = wVar.G0();
            uq2.baz bazVar = (uq2.baz) wVar.Xb.get();
            com.truecaller.qa.x xVar = (com.truecaller.qa.x) wVar.e0.get();
            jp2.qux quxVar = new jp2.qux((u03.z) wVar.M.get(), 1);
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(context, "context");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(yVar, "telecomOperatorDataQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(G0, "identifyWhatsAppNotificationManager");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(bazVar, "settingsRouter");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(xVar, "qaMenuSettings");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(quxVar, "ringSilentlyManager");
            ?? obj = new java.lang.Object();
            ((wt.l) obj).a = context;
            ((wt.l) obj).b = yVar;
            ((wt.l) obj).c = G0;
            ((wt.l) obj).d = bazVar;
            ((wt.l) obj).e = xVar;
            ((wt.l) obj).f = quxVar;
            x90.i iVar = new x90.i((android.content.Context) eVar2.i.a, (kotlin.coroutines.CoroutineContext) wVar.V1.get(), (kotlin.coroutines.CoroutineContext) wVar.P.get(), (com.truecaller.ads.util.k) wVar.Q9.get(), (jq2.bar) wVar.K9.get(), (r31.bar) wVar.q1.get(), (r90.a) wVar.ca.get(), cd3.baz.a(wVar.Fb), (y80.h) wVar.Ea.get(), cd3.baz.a(wVar.W9), cd3.baz.a(wVar.Aa), cd3.baz.a(wVar.G1), cd3.baz.a(wVar.sa), cd3.baz.a(c0Var.f5));
            android.content.Context context2 = (android.content.Context) eVar2.i.a;
            be0.e eVar3 = (be0.e) wVar.Dq.get();
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(context2, "context");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(eVar3, "announceCallerIdSettings");
            ?? obj2 = new java.lang.Object();
            ((dq1.h) obj2).a = context2;
            ((dq1.h) obj2).b = eVar3;
            android.content.Context context3 = (android.content.Context) eVar2.i.a;
            g92.bar barVar = (g92.bar) wVar.ji.get();
            dd2.h hVar2 = (dd2.h) wVar.ti.get();
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(context3, "context");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(barVar, "premiumShopDetailsDataStore");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(hVar2, "premiumVariantProvider");
            ?? obj3 = new java.lang.Object();
            ((k92.j) obj3).a = context3;
            ((k92.j) obj3).b = barVar;
            ((k92.j) obj3).c = hVar2;
            android.content.Context context4 = (android.content.Context) eVar2.i.a;
            q6.baz D0 = wVar.D0();
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(context4, "context");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(D0, "giveawaySourceCache");
            ?? obj4 = new java.lang.Object();
            ((f0.x0) obj4).a = context4;
            ((f0.x0) obj4).b = D0;
            a52.bar barVar2 = new a52.bar((android.content.Context) eVar2.i.a, 4);
            dn.qux quxVar2 = new dn.qux((android.content.Context) eVar2.i.a, cd3.baz.a(c0Var.x6));
            c52.qux quxVar3 = new c52.qux((android.content.Context) eVar2.i.a, 5);
            a11.h hVar3 = new a11.h((android.content.Context) eVar2.i.a, 4);
            f43.baz bazVar2 = new f43.baz((android.content.Context) eVar2.i.a, cd3.baz.a(wVar.fi), cd3.baz.a(wVar.ti), cd3.baz.a(wVar.Gi), cd3.baz.a(wVar.v1));
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter((java.lang.Object) obj2, "announceCallerQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter((java.lang.Object) obj3, "premiumShopDetailsQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter((java.lang.Object) obj4, "giveawayQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(barVar2, "premiumShowcaseQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(quxVar2, "premiumBannerQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(quxVar3, "premiumCatalogQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(hVar3, "bottomSheetQaMenuContributor");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(bazVar2, "ruleEngineQaMenuContributor");
            ?? obj5 = new java.lang.Object();
            ((ah.n) obj5).b = obj2;
            ((ah.n) obj5).a = obj3;
            ((ah.n) obj5).c = obj4;
            ((ah.n) obj5).d = barVar2;
            ((ah.n) obj5).e = quxVar2;
            ((ah.n) obj5).f = quxVar3;
            ((ah.n) obj5).g = hVar3;
            ((ah.n) obj5).h = bazVar2;
            qc3.bar a = cd3.baz.a(wVar2.I);
            qc3.bar a2 = cd3.baz.a(wVar2.N7);
            qc3.bar a3 = cd3.baz.a(wVar2.h5);
            qc3.bar a4 = cd3.baz.a(wVar2.Ih);
            qc3.bar a5 = cd3.baz.a(c0Var.D);
            qc3.bar a6 = cd3.baz.a(wVar2.W7);
            qc3.bar a7 = cd3.baz.a(wVar2.o1);
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a, "context");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a2, "dialAssistHelper");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a3, "callingSettings");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a4, "callUI");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a5, "callLogApi");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a6, "dialDiagnosticLogger");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a7, "callingFeaturesInventory");
            ?? obj6 = new java.lang.Object();
            ((wi.qux) obj6).a = a;
            ((wi.qux) obj6).b = a2;
            ((wi.qux) obj6).c = a3;
            ((wi.qux) obj6).d = a4;
            ((wi.qux) obj6).e = a5;
            ((wi.qux) obj6).f = a6;
            ((wi.qux) obj6).g = a7;
            wi.v vVar = new wi.v((android.content.Context) eVar2.i.a, c0Var.n0(), (oo1.f) wVar.m0.get(), (u03.q) wVar.Y1.get());
            hi2.c cVar = new hi2.c((android.content.Context) eVar2.i.a, (xz1.q) wVar.L0.get(), (com.truecaller.qa.x) wVar.e0.get(), cd3.baz.a(wVar.G1), cd3.baz.a(wVar.T2), (nc0.bar) wVar.Y.get(), (xd0.qux) wVar.Uf.get(), (t41.t) wVar.A1.get(), (u03.i0) c0Var.Q1.get(), (kotlin.coroutines.CoroutineContext) wVar.P.get(), (t41.baz) wVar.b2.get(), (y12.o0) wVar.m9.get(), (m02.g) wVar.ig.get(), (g02.bar) wVar.mh.get());
            qc3.bar a8 = cd3.baz.a(wVar.U2);
            android.content.Context context5 = (android.content.Context) eVar2.i.a;
            h93.baz bazVar3 = (h93.baz) wVar.t7.get();
            jq2.qux quxVar4 = (jq2.qux) wVar.M2.get();
            hr1.l lVar = (hr1.l) wVar.B6.get();
            qf0.bar barVar3 = (qf0.bar) wVar.Bk.get();
            com.truecaller.qa.x xVar2 = (com.truecaller.qa.x) wVar.e0.get();
            mk.e eVar4 = new mk.e((android.content.Context) wVar.I.get(), (qw2.a0) wVar.x6.get());
            a53.bar b0 = eVar2.b0();
            qw2.a0 a0Var = (qw2.a0) wVar.x6.get();
            b91.baz bazVar4 = new b91.baz(22);
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a8, "backgroundWorkTrigger");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(context5, "context");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(bazVar3, "wizardSettings");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(quxVar4, "generalSettings");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(lVar, "inAppUpdateSettings");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(barVar3, "appsFlyerEventsTracker");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(xVar2, "qaMenuSettings");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(eVar4, "callLogExporter");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(b0, "referralDialogLauncher");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a0Var, "tcPermissionsUtil");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(bazVar4, "blockLevelLauncher");
            ?? obj7 = new java.lang.Object();
            ((c62.b) obj7).a = a8;
            ((c62.b) obj7).b = context5;
            ((c62.b) obj7).c = bazVar3;
            ((c62.b) obj7).d = quxVar4;
            ((c62.b) obj7).e = lVar;
            ((c62.b) obj7).f = barVar3;
            ((c62.b) obj7).g = xVar2;
            ((c62.b) obj7).h = eVar4;
            ((c62.b) obj7).i = b0;
            ((c62.b) obj7).j = a0Var;
            ((c62.b) obj7).k = bazVar4;
            ((c62.b) obj7).l = com.truecaller.qa.user_growth.CallLogExporter$ExportOption.LAST_100;
            u21.bar barVar4 = new u21.bar((android.content.Context) eVar2.i.a, (com.truecaller.qa.x) wVar.e0.get(), (kotlin.coroutines.CoroutineContext) wVar.V1.get(), (s21.baz) c0Var.A6.get(), new b61.b(cd3.baz.a(c0Var.e), cd3.baz.a(wVar2.c0), 3));
            s01.l lVar2 = (s01.l) wVar.qj.get();
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(lVar2, "cloudTelephonySettings");
            ?? obj8 = new java.lang.Object();
            ((v2.j1) obj8).a = lVar2;
            qMActivity.S0 = new ah.f(jVar, hVar, m0Var, n0Var, bVar, (wt.l) obj, iVar, (ah.n) obj5, (wi.qux) obj6, vVar, cVar, (c62.b) obj7, barVar4, (v2.j1) obj8, new k0.h((h00.bar) c0Var.B6.get()), new a52.bar((android.content.Context) eVar2.i.a, 8), new ac1.e((com.truecaller.qa.x) wVar.e0.get(), (v23.bar) wVar.Dj.get(), c0Var.c5()));
            qMActivity.T0 = (com.truecaller.messaging.notifications.z) wVar.C3.get();
            qMActivity.U0 = (n11.l) wVar.o0.get();
            qMActivity.V0 = (gy.qux) wVar.Wk.get();
            qMActivity.W0 = (ev0.baz) c0Var.T5.get();
            qMActivity.X0 = wVar.O();
            qMActivity.Y0 = (nt2.qux) wVar.N5.get();
            qMActivity.Z0 = wVar.T();
            qMActivity.a1 = (m03.s) wVar.v1.get();
            qMActivity.b1 = wVar.A2();
            qMActivity.c1 = (w82.v) eVar2.k0.get();
            qMActivity.d1 = (t41.t) wVar.A1.get();
            qMActivity.e1 = (xd0.qux) wVar.G5.get();
            qMActivity.f1 = cd3.baz.a(wVar.Ph);
            qMActivity.g1 = cd3.baz.a(wVar.T2);
            qMActivity.h1 = (w82.q1) wVar.c4.get();
            qMActivity.i1 = (w82.y1) wVar.Bm.get();
            qMActivity.j1 = (i82.t) wVar.bc.get();
            qMActivity.k1 = (u62.b) wVar.Vb.get();
            qMActivity.l1 = (qw2.u) wVar.L6.get();
            qMActivity.m1 = (op1.h) c0Var.p4.get();
            qMActivity.n1 = (c62.q) wVar.t4.get();
            qMActivity.o1 = (qo1.r) wVar.V3.get();
            qc3.bar a9 = cd3.baz.a(wVar.V3);
            cu0.b bVar2 = (cu0.b) wVar.ao.get();
            n11.l lVar3 = (n11.l) wVar.o0.get();
            u03.b bVar3 = (u03.b) wVar.O.get();
            u03.z zVar = (u03.z) wVar.M.get();
            qw2.a0 a0Var2 = (qw2.a0) wVar.x6.get();
            u62.k kVar = (u62.k) wVar.N2.get();
            q83.qux quxVar5 = (q83.qux) wVar.u7.get();
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a9, "searchFeaturesInventory");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(bVar2, "notificationsManager");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(lVar3, "accountManager");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(bVar3, "deviceInfoUtil");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(zVar, "permissionUtil");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(a0Var2, "tcPermissionUtil");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(kVar, "throttler");
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(quxVar5, "wizard");
            nd.g gVar = nd.g.b;
            qMActivity.p1 = (com.truecaller.data.country.g) wVar.H1.get();
            qMActivity.q1 = wVar.K3();
            qMActivity.r1 = (hb2.baz) c0Var.z4.get();
            qMActivity.s1 = c0Var.f1();
            qMActivity.t1 = wVar.y();
            qMActivity.u1 = (com.truecaller.remoteconfig.firebase.baz) wVar.J.get();
            qMActivity.v1 = eVar2.m0;
            qMActivity.w1 = (q83.a) wVar.Sb.get();
            qMActivity.x1 = (dj0.baz) wVar.Yn.get();
            qMActivity.y1 = (cm0.qux) c0Var.i2.get();
            qMActivity.z1 = (s62.d) wVar.P2.get();
            qMActivity.A1 = (nd1.bar) wVar.dm.get();
        }
    }
}
